atmosphere-grid:
  bottom: 0.0
  top: atmospherefile
  number-of-layers: 100

planet:
  planet-mass: 4.132740e+27 # 0.692x Earth mass (grams) Agol et al. (2021)
  planet-radius: 5.867852e+08 # 0.920x Earth Radius (cm) Agol et al. (2021)
  surface-albedo: 0.1
  solar-zenith-angle: 60.0
  hydrogen-escape:
    type: diffusion limited
  water: {fix-water-in-troposphere: false, gas-rainout: false, water-condensation: false}

particles:
- {name: H2Oaer, RH-condensation: 0.5}

boundary-conditions:
# The ocean
- name: H2O
  lower-boundary: {type: press, press: 270.0e6} # 270 bar H2O (1 ocean)
  upper-boundary: {type: veff, veff: 0.0}

# Deposition velocities reflecting the consumption of these gases by life 
# (Kharecha et al. 2005), and also a volcanic flux
- name: CO
  lower-boundary: {type: vdep + dist flux, vdep: 1.2e-4, flux: 1e9, height: -1}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2
  lower-boundary: {type: vdep + dist flux, vdep: 2.4e-4, flux: 1e10, height: -1}
  upper-boundary: {type: veff, veff: 0.0}

# Several boundary conditions following Ranjan et al. (2023), ApJ
- name: H2CO
  lower-boundary: {type: vdep, vdep: 0.1}
  upper-boundary: {type: veff, veff: 0.0}
- name: C2H6
  lower-boundary: {type: vdep, vdep: 1.0e-5}
  upper-boundary: {type: veff, veff: 0.0}
- name: NO
  lower-boundary: {type: vdep + dist flux, vdep: 0.02, flux: 1e8, height: -1} # From lightning
  upper-boundary: {type: veff, veff: 0.0}
- name: HCN
  lower-boundary: {type: vdep, vdep: 7.0e-3}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCCCN
  lower-boundary: {type: vdep, vdep: 7.0e-3}
  upper-boundary: {type: veff, veff: 0.0}

# Short lived species
- name: O1D
  type: short lived
- name: N2D
  type: short lived
