atmosphere-grid:
  bottom: 0.0
  top: atmospherefile
  number-of-layers: 100

planet:
  planet-mass: 5.972e27
  planet-radius: 6.371e8
  surface-albedo: 0.25
  solar-zenith-angle: 60.0
  hydrogen-escape:
    type: diffusion limited
  water:
    fix-water-in-troposphere: false
    gas-rainout: false
    water-condensation: false

particles:
- {name: H2Oaer, RH-condensation: 0.5}

boundary-conditions:
- name: N2
  lower-boundary: {type: press, press: 1.0e6} # in dynes/cm^2
  upper-boundary: {type: veff, veff: 0.0}
- name: CO2
  lower-boundary: {type: press, press: 0.1e6} # in dynes/cm^2
  upper-boundary: {type: veff, veff: 0.0}
- name: CH4
  lower-boundary: {type: flux, flux: 1e11} # in molecules/cm^2/s
  upper-boundary: {type: veff, veff: 0.0}

# Don't change anything below
- name: H2O
  lower-boundary: {type: press, press: 270.0e6} # 270 bar H2O (1 ocean)
  upper-boundary: {type: veff, veff: 0.0}
- name: CO
  lower-boundary: {type: vdep + dist flux, vdep: 1.2e-4, flux: 1e9, height: -1}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2
  lower-boundary: {type: vdep + dist flux, vdep: 2.4e-4, flux: 1e10, height: -1}
  upper-boundary: {type: veff, veff: 0.0}